// Generated by generate_board_vectors.py; book examples plus boundary cases.
function [9:0] test_input;
    input [3:0] index;
    begin
        case (index)
            4'd0: test_input = 10'h034;
            4'd1: test_input = 10'h3c1;
            4'd2: test_input = 10'h05c;
            4'd3: test_input = 10'h050;
            4'd4: test_input = 10'h357;
            4'd5: test_input = 10'h3c0;
            4'd6: test_input = 10'h3c3;
            4'd7: test_input = 10'h010;
            4'd8: test_input = 10'h0d0;
            4'd9: test_input = 10'h155;
            4'd10: test_input = 10'h3d7;
            4'd11: test_input = 10'h017;
            4'd12: test_input = 10'h350;
            4'd13: test_input = 10'h11c;
            4'd14: test_input = 10'h14c;
            4'd15: test_input = 10'h15c;
        endcase
    end
endfunction
function [23:0] test_expected;
    input [3:0] index;
    begin
        case (index)
            4'd0: test_expected = 24'h0c1408;
            4'd1: test_expected = 24'hf0d500;
            4'd2: test_expected = 24'h3f1420;
            4'd3: test_expected = 24'h14041c;
            4'd4: test_expected = 24'hd5cbc0;
            4'd5: test_expected = 24'hf03000;
            4'd6: test_expected = 24'hf0e100;
            4'd7: test_expected = 24'h04200d;
            4'd8: test_expected = 24'h340012;
            4'd9: test_expected = 24'h554ffc;
            4'd10: test_expected = 24'hf4d700;
            4'd11: test_expected = 24'h07d40c;
            4'd12: test_expected = 24'hc01440;
            4'd13: test_expected = 24'hcf1480;
            4'd14: test_expected = 24'hf31500;
            4'd15: test_expected = 24'h5707a0;
        endcase
    end
endfunction
